# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       phonon-qt5-gstreamer

# >> macros
# << macros

Summary:    Multimedia framework api
Version:    4.7.80
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  phonon-qt5-gstreamer.yaml
Source101:  phonon-qt5-gstreamer-rpmlintrc
Patch0:     0001-Find-the-right-Phonon-version.patch
Requires:   kf5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5OpenGL)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(gstreamer-1.0)
BuildRequires:  pkgconfig(gstreamer-plugins-base-1.0)
BuildRequires:  cmake
BuildRequires:  kf5-rpm-macros
BuildRequires:  qt5-tools
BuildRequires:  phonon-qt5-devel

%description
Multimedia framework api


%prep
%setup -q -n %{name}-%{version}/upstream

# 0001-Find-the-right-Phonon-version.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
%kf5_make -DPHONON_BUILD_PHONON4QT5:BOOL=ON
# << build pre



# >> build post
%kf5_make_install
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING.LIB
%{_qt5_plugindir}/phonon4qt5_backend/*
# >> files
# << files
